SAMPLE_COMPETITIONS = [
    {
        "class": "competition",
        "url": "https://www.worldcubeassociation.org/competitions/FranconiaFall2019",
        "id": "FranconiaFall2019",
        "name": "Franconia Fall 2019",
        "website": "https://www.worldcubeassociation.org/competitions/FranconiaFall2019",
        "short_name": "Franconia Fall 2019",
        "city": "Nürnberg",
        "venue_address": "Kirchgasse 6, 90607 Rückersdorf",
        "venue_details": "",
        "latitude_degrees": 49.49267,
        "longitude_degrees": 11.24286,
        "country_iso2": "DE",
        "start_date": "2019-10-12",
        "announced_at": "2019-06-16T19:21:04.000Z",
        "end_date": "2019-10-13",
        "delegates": [
            {
                "class": "user",
                "url": "https://www.worldcubeassociation.org/persons/2011FRES01",
                "id": 7056,
                "wca_id": "2011FRES01",
                "name": "Linus Frész",
                "gender": "m",
                "country_iso2": "DE",
                "delegate_status": "delegate",
                "created_at": "2015-12-16T12:06:03.000Z",
                "updated_at": "2019-08-12T19:35:41.000Z",
                "teams": [],
                "avatar": {
                    "url": "https://www.worldcubeassociation.org/uploads/user/avatar/2011FRES01/1530273532.jpg",
                    "thumb_url": "https://www.worldcubeassociation.org/uploads/user/avatar/2011FRES01/1530273532_thumb.jpg",
                    "is_default": False,
                },
                "email": "lfresz@worldcubeassociation.org",
                "region": "Germany",
                "senior_delegate_id": 870,
            }
        ],
        "organizers": [
            {
                "class": "user",
                "url": "https://www.worldcubeassociation.org/persons/2010SCHM01",
                "id": 393,
                "wca_id": "2010SCHM01",
                "name": "Leon Schmidtchen",
                "gender": "m",
                "country_iso2": "DE",
                "delegate_status": None,
                "created_at": "2015-06-02T20:21:41.000Z",
                "updated_at": "2019-08-09T18:55:16.000Z",
                "teams": [{"friendly_id": "wqac", "leader": False}],
                "avatar": {
                    "url": "https://www.worldcubeassociation.org/uploads/user/avatar/2010SCHM01/1554061656.jpg",
                    "thumb_url": "https://www.worldcubeassociation.org/uploads/user/avatar/2010SCHM01/1554061656_thumb.jpg",
                    "is_default": False,
                },
            }
        ],
        "event_ids": [
            "333",
            "222",
            "444",
            "555",
            "666",
            "777",
            "333bf",
            "333oh",
            "pyram",
            "skewb",
        ],
    },
    {
        "class": "competition",
        "url": "https://www.worldcubeassociation.org/competitions/MunichOpen2019",
        "id": "MunichOpen2019",
        "name": "Munich Open 2019",
        "website": "https://www.worldcubeassociation.org/competitions/MunichOpen2019",
        "short_name": "Munich Open 2019",
        "city": "Unterhaching",
        "venue_address": "Grünauer-Allee 6, 82008 Unterhaching",
        "venue_details": "",
        "latitude_degrees": 48.06337,
        "longitude_degrees": 11.62089,
        "country_iso2": "DE",
        "start_date": "2019-11-02",
        "announced_at": "2019-03-05T19:17:16.000Z",
        "end_date": "2019-11-03",
        "delegates": [
            {
                "class": "user",
                "url": "https://www.worldcubeassociation.org/persons/2014PETE03",
                "id": 76,
                "wca_id": "2014PETE03",
                "name": "Tobias Peter",
                "gender": "m",
                "country_iso2": "CH",
                "delegate_status": "candidate_delegate",
                "created_at": "2015-05-23T16:01:10.000Z",
                "updated_at": "2019-08-04T23:35:10.000Z",
                "teams": [],
                "avatar": {
                    "url": "https://www.worldcubeassociation.org/uploads/user/avatar/2014PETE03/1535923164.jpeg",
                    "thumb_url": "https://www.worldcubeassociation.org/uploads/user/avatar/2014PETE03/1535923164_thumb.jpeg",
                    "is_default": False,
                },
                "email": "tpeter@worldcubeassociation.org",
                "region": "Switzerland",
                "senior_delegate_id": 870,
            },
            {
                "class": "user",
                "url": "https://www.worldcubeassociation.org/persons/2011GRIT01",
                "id": 140,
                "wca_id": "2011GRIT01",
                "name": "Oleg Gritsenko",
                "gender": "m",
                "country_iso2": "RU",
                "delegate_status": "delegate",
                "created_at": "2015-05-26T09:10:01.000Z",
                "updated_at": "2019-08-04T17:26:09.000Z",
                "teams": [{"friendly_id": "wrc", "leader": False}],
                "avatar": {
                    "url": "https://www.worldcubeassociation.org/uploads/user/avatar/2011GRIT01/1441150544.jpg",
                    "thumb_url": "https://www.worldcubeassociation.org/uploads/user/avatar/2011GRIT01/1441150544_thumb.jpg",
                    "is_default": False,
                },
                "email": "ogritsenko@worldcubeassociation.org",
                "region": "Switzerland",
                "senior_delegate_id": 870,
            },
            {
                "class": "user",
                "url": "https://www.worldcubeassociation.org/persons/2011FRES01",
                "id": 7056,
                "wca_id": "2011FRES01",
                "name": "Linus Frész",
                "gender": "m",
                "country_iso2": "DE",
                "delegate_status": "delegate",
                "created_at": "2015-12-16T12:06:03.000Z",
                "updated_at": "2019-08-12T19:35:41.000Z",
                "teams": [],
                "avatar": {
                    "url": "https://www.worldcubeassociation.org/uploads/user/avatar/2011FRES01/1530273532.jpg",
                    "thumb_url": "https://www.worldcubeassociation.org/uploads/user/avatar/2011FRES01/1530273532_thumb.jpg",
                    "is_default": False,
                },
                "email": "lfresz@worldcubeassociation.org",
                "region": "Germany",
                "senior_delegate_id": 870,
            },
        ],
        "organizers": [
            {
                "class": "user",
                "url": "https://www.worldcubeassociation.org/persons/2010SCHM01",
                "id": 393,
                "wca_id": "2010SCHM01",
                "name": "Leon Schmidtchen",
                "gender": "m",
                "country_iso2": "DE",
                "delegate_status": None,
                "created_at": "2015-06-02T20:21:41.000Z",
                "updated_at": "2019-08-09T18:55:16.000Z",
                "teams": [{"friendly_id": "wqac", "leader": False}],
                "avatar": {
                    "url": "https://www.worldcubeassociation.org/uploads/user/avatar/2010SCHM01/1554061656.jpg",
                    "thumb_url": "https://www.worldcubeassociation.org/uploads/user/avatar/2010SCHM01/1554061656_thumb.jpg",
                    "is_default": False,
                },
            },
            {
                "class": "user",
                "url": "https://www.worldcubeassociation.org/persons/2011FRES01",
                "id": 7056,
                "wca_id": "2011FRES01",
                "name": "Linus Frész",
                "gender": "m",
                "country_iso2": "DE",
                "delegate_status": "delegate",
                "created_at": "2015-12-16T12:06:03.000Z",
                "updated_at": "2019-08-12T19:35:41.000Z",
                "teams": [],
                "avatar": {
                    "url": "https://www.worldcubeassociation.org/uploads/user/avatar/2011FRES01/1530273532.jpg",
                    "thumb_url": "https://www.worldcubeassociation.org/uploads/user/avatar/2011FRES01/1530273532_thumb.jpg",
                    "is_default": False,
                },
                "email": "lfresz@worldcubeassociation.org",
                "region": "Germany",
                "senior_delegate_id": 870,
            },
        ],
        "event_ids": ["333", "222", "444", "555", "333bf", "333oh", "pyram", "skewb"],
    },
]

